### ISSUE TITLE
code develop time

### ISSUE THREAD

**Issue by niwota865** [akamud/FlatSpark#5]
When will it be developed?I am very interested in the skin

**Comment by yozef** [comment]
what component's skin exactly? (it's fairly easy to extend it yourself) @akamud lib is a awesome start.

**Comment by akamud** [comment]
Hi @niwota865, it is already being developed. In fact, it is now officially part of the Apache Flex framework.
You can use it with Apache Flex 4.14, you can see instructions on how to use it [here](https://cwiki.apache.org/confluence/display/FLEX/Using+FlatSpark+skins).

If you want to browse the source code, it is hosted [here](https://github.com/apache/flex-sdk/tree/develop/frameworks/projects/flatspark)

**Comment by niwota865** [comment]
The dataGrid flatter most needed now

77777_0000@sina.com

From: Joseph
Date: 2015-02-28 20:09
To: akamud/FlatSpark
CC: niwota865
Subject: Re: [FlatSpark] code develop time (#5)
what component's skin exactly? (it's fairly easy to extend it yourself) @akamud lib is a awesome start.

**Comment by akamud** [comment]
Indeed the DataGrid component is still missing. If you wish to help with the development, you can do so in the Flex repository.
We plan to update all the missing components in FlatSpark, but honestly we are struggling to find the time to do it, so any help is appreciated.

**Comment by niwota865** [comment]
Through your answer, does that mean the datagrid updates for a period of time?

**Comment by niwota865** [comment]
The flattening of the skin is good, but is just the beginning, I really hope this can complete the skin a bit

**Comment by akamud** [comment]
That's exactly why we released this, even though it is incomplete, we had a start and wanted to get help from others.

We have no release date for the DataGrid component right now.

**Comment by niwota865** [comment]
I will continue focus on this, hope you as soon as possible release full version

**Comment by justein** [comment]
May we can improve the flatSpark skin.

**Comment by akamud** [comment]
Hi @justein, any further development must be made with Apache Flex version, as it is now officially part of Flex 4.14. You can see it [here](https://github.com/apache/flex-sdk/tree/develop/frameworks/projects/flatspark)
